#!/bin/bash

window=$(xdotool getactivewindow)

set -- junk $(cat ~/.config/emoji ~/.config/kaomoji ~/.config/emojenu-custom-chars/* | dmenu -p emoji -fn 'FiraCode-15' -l 15 -i $1)

shift

if [ $# -eq 0 ]; then
    exit
fi

echo $@

emoji=$(echo $@ |  cut -d '|' -f 2 | tr -s '\r')

printf "$emoji" | xclip -selection clipboard

xdotool windowactivate $window
