#!/bin/bash

window=$(xdotool getactivewindow)

set -- junk $(cat ~/.config/emoji ~/.config/kaomoji ~/.config/emojenu-custom-chars | cut -d '|' -f 1 | dmenu -p emoji)

shift

if [ $# -eq 0 ]; then
    exit
fi

emoji=$(cat ~/.config/emoji ~/.config/kaomoji ~/.config/emojenu-custom-chars | grep "^$(echo $@)|" | cut -d '|' -f 2 | tr -s '\r')

printf "$emoji" | xclip -selection clipboard

xdotool windowactivate $window
